#!/usr/bin/env bash
# Bash script that display.
    # create a file when its executed.
    # a message in an infinity loop.
    # a message when receiving a SIGTERM signal.
    # a message when receiving a SIGINT signal.
    # delete a file and finish when receiving a SIGOUT/SIGTERM signal.

echo "$$" > /var/run/holbertonscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
