#!/usr/bin/env bash
# while loop with multiple if statement.

c=1
while [ $c -le 10 ] #left or equal to
do
    if [ "$c" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$c" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((c++))
done
