#!/usr/bin/env bash
#

c=1
while [ $c -le 20 ] #left or equal
do
    echo "$c"
    case "${c}"
    in
        4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    ((c++))
done