#!/usr/bin/env bash
#clock - print hours and minutes

h=0
m=1
while [ $h -le 12 ] # less or equal - Hour
do
    m=1
    echo "Hour: $h"
    while [ $m -lt 60 ] #less than - minutes
    do
	echo $m
	((m++))
    done
    ((h++))
done