#!/usr/bin/env bash
#Script that gives you information about the Holbertonschool file.

#loc=$(.)
file="holbertonschool"
if [ -e "$file" ] # check with -e if the file exists
then
    echo "$file file exists"
    if [ -s "$file" ]
    then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi
    if [ -f "$file" ]
    then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi